services:
  - type: web
    name: audio-scrapper
    env: node
    buildCommand: cd BACKEND && npm install
    startCommand: cd BACKEND && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: HEADLESS
        value: true
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
    plan: free
